# 워크플로우의 이름
name: Deploy Backend to AWS EC2

# 이 워크플로우가 언제 실행될지를 정의합니다.
on:
  push:
    branches:
      - main

# 수행할 작업(job)들을 정의합니다.
jobs:
  deploy:
    # 이 작업이 실행될 가상 환경을 지정합니다.
    runs-on: ubuntu-latest

    # 작업이 수행할 단계(step)들을 순서대로 나열합니다.
    steps:
      # 1단계: EC2에 접속하여 배포 스크립트를 실행
      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.AWS_HOST }}
          username: ${{ secrets.AWS_USER }}
          key: ${{ secrets.AWS_KEY }}
          
          # EC2 서버에 접속해서 실행할 명령어들을 순서대로 적습니다.
          script: |
            # --- [ 핵심 수정 부분 ] ---
            # 1. NVM(Node Version Manager) 환경을 로드합니다.
            #    -> 이 부분이 npm, npx, pm2 명령어를 사용할 수 있게 해줍니다.
            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
            
            # 2. 프로젝트 폴더로 이동합니다.
            cd ~/zk-vote

            # 3. GitHub 저장소에서 최신 코드를 내려받습니다.
            git pull origin main

            # 4. 프로젝트 루트의 의존성을 설치합니다. (hardhat 등)
            npm install

            # 5. Hardhat을 이용해 스마트 컨트랙트를 컴파일합니다.
            npx hardhat compile

            # 6. 서버(백엔드) 폴더로 이동합니다.
            cd server

            # 7. 서버의 의존성을 설치합니다.
            npm install
            
            # 8. .env 파일을 GitHub Secrets를 이용해 생성합니다.
            echo "SEPOLIA_RPC_URL=${{ secrets.SEPOLIA_RPC_URL }}" >> .env
            echo "PRIVATE_KEY=${{ secrets.PRIVATE_KEY }}" >> .env
            echo "SUPABASE_URL=${{ secrets.SUPABASE_URL }}" >> .env
            echo "SUPABASE_KEY=${{ secrets.SUPABASE_KEY }}" >> .env
            echo "SECRET_SALT=${{ secrets.SECRET_SALT }}" >> .env
            echo "REDIS_HOST=${{ secrets.REDIS_HOST }}" >> .env
            echo "REDIS_PORT=${{ secrets.REDIS_PORT }}" >> .env
            # 필요한 다른 모든 환경 변수를 이와 같이 추가합니다.

            # 9. PM2로 서버를 다시 시작하거나 새로 시작합니다.
            pm2 reload zk-vote-api || pm2 start index.js --name zk-vote-api