# 워크플로우의 이름
name: Deploy Backend to AWS EC2

# 이 워크플로우가 언제 실행될지를 정의합니다.
# -> 'main' 브랜치에 'push' 이벤트가 발생했을 때
on:
  push:
    branches:
      - main

# 수행할 작업(job)들을 정의합니다.
jobs:
  # 'deploy'라는 이름의 작업을 정의합니다.
  deploy:
    # 이 작업이 실행될 가상 환경을 지정합니다. -> 최신 우분투
    runs-on: ubuntu-latest

    # 작업이 수행할 단계(step)들을 순서대로 나열합니다.
    steps:
      # 1단계: EC2에 접속하여 배포 스크립트를 실행
      - name: Deploy to EC2
        # SSH 접속 및 명령어 실행을 쉽게 해주는 유명한 GitHub Action을 사용합니다.
        uses: appleboy/ssh-action@master
        # 이 Action에 필요한 값들을 전달합니다.
        with:
          # host, username, key는 1단계에서 GitHub Secrets에 저장한 값을 사용합니다.
          host: ${{ secrets.AWS_HOST }}
          username: ${{ secrets.AWS_USER }}
          key: ${{ secrets.AWS_KEY }}
          
          # EC2 서버에 접속해서 실행할 명령어들을 순서대로 적습니다.
          script: |
            # 1. 프로젝트 폴더로 이동합니다.
            cd ~/zk-vote

            # 2. GitHub 저장소에서 최신 코드를 내려받습니다.
            git pull origin main

            # 3. 서버(백엔드) 폴더로 이동합니다.
            cd server

            # 4. GitHub Secret에 저장된 내용으로 .env 파일을 생성(덮어쓰기)합니다.
            echo "${{ secrets.ENV_FILE }}" > .env

            # 5. 변경된 package.json에 맞춰 라이브러리를 설치합니다.
            npm install

            # 6. PM2로 실행 중인 서버를 최신 코드로 다시 시작합니다.
            pm2 restart zk-vote-api